### ISSUE TITLE
add_machine_options fails on azure

### ISSUE THREAD

**Issue by vinyar** [chef/chef-provisioning-azure#19]
Seems that when with_machine_options is defined and add_machine_options is used with machine resource, the hash merge breaks somewhere internally. 

I couldn't figure out exactly where the cause is, but here is an example in the gist: https://gist.github.com/vinyar/9413dd79e1e80977643c

The result is :os_type error
vm = azure_vm_service.create_virtual_machine(params, bootstrap_options)
error => "Unexpected method []= for MergedConfig with arguments [:os_type, \"Linux\”]"

**Comment by vinyar** [comment]
It should probably have some try/catch logic, in case vm = .. fails, the error should be presented in STDOUT, and the recipe should exit. As it is now, the error is very generic

```pry output
Compiling Cookbooks...
Converging 10 resources
Recipe: delivery-cluster::setup_chef_server
  * machine[chef-server-alexv] action converge
    - Creating chef-server-alexv with image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140927-en-us-30GB in West US...WARN: Unresolved specs during Gem::Specification.reset:
      httpclient (>= 2.2.0.2, ~> 2.2)
      gyoku (>= 0.4.0)
      mini_portile (~> 0.6.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

From: /Users/alexvinyar/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-azure-0.2.1/lib/chef/provisioning/azure_driver/driver.rb @ line 116 Chef::Provisioning::AzureDriver::Driver#allocate_machine:

    111:         }
    112:         # require 'pry';binding.pry
    113:         action_handler.report_progress "Creating #{machine_spec.name} with image #{image_id} in #{location}..."
    114:         vm = azure_vm_service.create_virtual_machine(params, bootstrap_options)
    115:       end
 => 116:       require 'pry';binding.pry
    117:       machine_spec.location['vm_name'] = vm.vm_name
    118:       action_handler.report_progress "Created #{vm.vm_name} in #{location}..."
    119:     end
    120:
    121:     # (see Chef::Provisioning::Driver#ready_machine)

2.1.4 (#<Chef::Provisioning::AzureDriver::Driver:0x007fc3f2c781a8>):0 > params
=> {
     :image => "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140927-en-us-30GB",
  :location => "West US",
  :password => "chefm3t4lB/la\\",
   :vm_name => "chef-server-alexv",
   :vm_user => "ubuntu"
}
2.1.4 (#<Chef::Provisioning::AzureDriver::Driver:0x007fc3f2c781a8>):0 > bootstrap_options
=> {
    :cloud_service_name => "alexvchefserver01",
              :location => "West US",
  :storage_account_name => "alexvstorageacct02",
               :vm_size => "Medium"
}
2.1.4 (#<Chef::Provisioning::AzureDriver::Driver:0x007fc3f2c781a8>):0 > azure_vm_service.create_virtual_machine
ArgumentError: wrong number of arguments (0 for 1..2)
from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/azure-0.6.4/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:106:in `create_virtual_machine'
2.1.4 (#<Chef::Provisioning::AzureDriver::Driver:0x007fc3f2c781a8>):0 > vm = azure_vm_service.create_virtual_machine(params, bootstrap_options)
=> "Unexpected method []= for MergedConfig with arguments [:os_type, \"Linux\"]"
2.1.4 (#<Chef::Provisioning::AzureDriver::Driver:0x007fc3f2c781a8>):0 > [2015-03-25T05:20:11-07:00] FATAL: SIGINT received, stopping
[2015-03-25T05:20:11-07:00] FATAL: SIGINT received, stopping
[2015-03-25T05:20:11-07:00] FATAL: SIGINT received, stopping

    ================================================================================
    Error executing action `converge` on resource 'machine[chef-server-alexv]'
    ================================================================================

    SystemExit
    ----------
    exit

    Resource Declaration:
    ---------------------
    # In /Users/alexvinyar/Documents/Projects/deliverance/delivery-cluster_chefconf2015/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/delivery-cluster/recipes/setup_chef_server.rb

     21: machine chef_server_hostname do # basically chef-server-alexv
     22:   # case node['delivery-cluster']['cloud']
     23:   # when 'azure'
     24:     add_machine_options bootstrap_options: { cloud_service_name: node['delivery-cluster']['chef-server']['cloud_service_name'] } if node['delivery-cluster']['chef-server']['cloud_service_name']
     25:   #   # add_machine_options bootstrap_options: { :storage_account_name node['delivery-cluster']['chef-server']['azureflavor'] } if node['delivery-cluster']['chef-server']['azureflavor']
     26:   # when 'aws'
     27:   #   add_machine_options bootstrap_options: { instance_type: node['delivery-cluster']['chef-server']['flavor'] } if node['delivery-cluster']['chef-server']['flavor']
     28:   # end
     29:   # Transfer any trusted certs from the current CCR

    Compiled Resource:
    ------------------
    # Declared in /Users/alexvinyar/Documents/Projects/deliverance/delivery-cluster_chefconf2015/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/delivery-cluster/recipes/setup_chef_server.rb:21:in `from_file'

    machine("chef-server-alexv") do
      action [:converge]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"http://localhost:8889", :options=>{:client_name=>"delivery", :signing_key_filename=>nil}}
      driver "azure"
      machine_options #<Cheffish::MergedConfig:0x007fc3f951fcb0 @configs=[{:bootstrap_options=>{:cloud_service_name=>"alexvchefserver01"}}, {:bootstrap_options=>{:vm_size=>"Medium", :location=>"West US", :storage_account_name=>"alexvstorageacct02"}, :image_id=>"b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140927-en-us-30GB", :password=>"chefm3t4lB/la\\"}], @merge_arrays={}>
      declared_type :machine
      cookbook_name "delivery-cluster"
      recipe_name "setup_chef_server"
    end


```

**Comment by stuartpreston** [comment]
Hi @vinyar is this still an issue for you?  It has been quite a while since this was opened and I suspect a re-test against the latest bits will yield a different result. I'm closing this out for now but please re-open if it is blocking you.

**Comment by vinyar** [comment]
Hadn't played with azure provisioning for a while ... I dont know. I hope not :+1:
