### ISSUE TITLE
Chef::Provisioning::AzureDriver::Driver does not implement connect_to_machine

### ISSUE THREAD

**Issue by vinyar** [chef/chef-provisioning-azure#21]
* machine_file[chef-server-cert] action download   
    Error executing action `download` on resource 'machine_file[chef-server-cert]'
   RuntimeError
    ------------
    Chef::Provisioning::AzureDriver::Driver does not implement connect_to_machine

Didnt have a chance to go code diving on this one. For now filing an issue as is.

Recipe:
```ruby
machine_file 'chef-server-cert' do
  path lazy { "/var/opt/opscode/nginx/ca/#{chef_server_ip}.crt" }
  machine chef_server_hostname
  local_path lazy { "#{Chef::Config[:trusted_certs_dir]}/#{chef_server_ip}.crt" }
  action :download
end
```

**Comment by vinyar** [comment]
Tried the new branch. No workie.
pry:
```ruby
2.1.4 (#<Chef::Provisioning::AzureDriver::Driver:0x007fbdded8a858>):0 > whereami

From: /Users/alexvinyar/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-azure-0.2.1/lib/chef/provisioning/azure_driver/driver.rb @ line 145 Chef::Provisioning::AzureDriver::Driver#connect_to_machine:

    144: def connect_to_machine(name, chef_server = nil)
 => 145:   require 'pry';binding.pry
    146:   if name.is_a?(MachineSpec)
    147:     machine_spec = name
    148:   else
    149:     machine_spec = Chef::Provisioning::ChefMachineSpec.get(name, chef_server)
    150:   end
    151:
    152:   machine_for(machine_spec, machine_spec.reference)
    153: end

2.1.4 (#<Chef::Provisioning::AzureDriver::Driver:0x007fbdded8a858>):0 > name.is_a?(MachineSpec)
=> true
2.1.4 (#<Chef::Provisioning::AzureDriver::Driver:0x007fbdded8a858>):0 > machine_for(name, machine_spec.reference)
NoMethodError: undefined method `reference' for nil:NilClass
from (pry):13:in `connect_to_machine'
2.1.4 (#<Chef::Provisioning::AzureDriver::Driver:0x007fbdded8a858>):0 > name.re
name.remove_instance_variable       name.respond_to?                    name.restore_wow64_file_redirection
2.1.4 (#<Chef::Provisioning::AzureDriver::Driver:0x007fbdded8a858>):0 > name.re
```

Stack Trace:
```ruby
Generated at 2015-03-26 02:48:07 -0700
SystemExit: machine_file[chef-server-cert] (delivery-cluster::setup_chef_server line 58) had an error: SystemExit: exit
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:389:in `exit'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:389:in `fatal!'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:63:in `block in setup_signal_handlers'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:198:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:198:in `readline'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:198:in `block in input_readline'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/input_lock.rb:115:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/input_lock.rb:115:in `interruptible_region'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:197:in `input_readline'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:183:in `block in read_line'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:129:in `handle_read_errors'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:170:in `read_line'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:98:in `read'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:68:in `block in repl'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:67:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:67:in `repl'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:38:in `block in start'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `__with_ownership'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/input_lock.rb:79:in `with_ownership'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:38:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:15:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_class.rb:169:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/core_extensions.rb:43:in `pry'
/Users/alexvinyar/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-azure-0.2.1/lib/chef/provisioning/azure_driver/driver.rb:145:in `connect_to_machine'
/Users/alexvinyar/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provisioning.rb:91:in `connect_to_machine'
/Users/alexvinyar/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provisioning/chef_run_data.rb:100:in `connect_to_machine'
/Users/alexvinyar/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provider/machine_file.rb:24:in `machine'
/Users/alexvinyar/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provider/machine_file.rb:45:in `block in <class:MachineFile>'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/apps/chef/lib/chef/client.rb:315:in `converge'
/opt/chefdk/embedded/apps/chef/lib/chef/client.rb:400:in `block in run'
/opt/chefdk/embedded/apps/chef/lib/chef/client.rb:399:in `catch'
/opt/chefdk/embedded/apps/chef/lib/chef/client.rb:399:in `run'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:355:in `block in interval_run_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:345:in `loop'
/opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:345:in `interval_run_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:335:in `run_application'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chefdk/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:40:in `load'
/usr/bin/chef-client:40:in `<main>'
```

**Comment by stuartpreston** [comment]
Which 'new branch' are you referring to?

Machine_file or anything that involves operations on the machine after initial provisioning definitely haven't been tested by me - first aim has been to get some of the other resources doing the right thing via the Azure API (see the readme for a list of things that are still outstanding)

**Comment by vinyar** [comment]
Last night Keiser hacked up a branch as an experiment to get machine_file working - https://github.com/chef/chef-provisioning-azure/tree/jk/connect_to_machine

**Comment by irvingpop** [comment]
Playing around with that branch, I see why it's not working. 

Here: https://github.com/chef/chef-provisioning-azure/blob/jk/connect_to_machine/lib/chef/provisioning/azure_driver/driver.rb#L145
it is passing `machine_spec.reference` to `machine_for`.   But that doesn't contain `:convergence_options` and normally that wouldn't be a problem (we could `|| {}` in `convergence_strategy_for` like other drivers).   

However, in the case of this driver it needs to get the password out of `:convergence_options` -  but I can't figure out how to get those back in the context of `connect_to_machine`.   @jkeiser any ideas?

**Comment by vinyar** [comment]
I had a hack somewhere for that a long time ago.... cant find the code, but it may be in one of the bugs.  
IIRC - there is a chunk of code that stores attributes and attaches them to node object, I tacked on IP and password to it.. which is obviously a horrible idea, but it unblocked me.

**Comment by stuartpreston** [comment]
Closing this as we will not fix the ASM driver.  Azure Resource Manager further complicates things by not insisting that each machine even has a public SSH or WinRM port.  Instead we will be using the cloud api to install the Chef-Client, perform self-registration.  Getting files on the machine will require some creative thinking in future.  If you need further information please DM me (email on profile).
